### ISSUE TITLE
How to construct .feature and .label file

### ISSUE THREAD

**Issue by miqbal23** [jvking/bp-lda#5]
Hello, I have question regarding the input file.

In every dataset you used (both Amazon and MultiSent), there are 2 type of file being used as input : `.feature` and `.label`, while there's one additional  `vocab.txt` file. I saw the content of `.label` and it's pretty straightforward, but still confused on `.feature` file.

May I know how do you construct the `.feature` file? I tried to replicate your code by using different set of data.

**Comment by jvking** [comment]
Sure.

.feature: each line is a document in bag-of-words representation. Colon is
used to delimit word index and word counts. Tab is used to delimit
different words.

An example line would look like this:
29:3 52:1 103:1 139:1 1685:1 245:1 130:1 2194:1 212:1 4:7 1003:1 77:2 95:1
1376:1 423:1 113:1 201:1 23:5 143:1 445:1 54:1 3101:1 257:1 82:1 46:2 13:1
12:2 255:1 285:1

Let me know if you still have questions. Thanks for your interests in using
the package!

**Comment by miqbal23** [comment]
I see the `vocab.txt ` file is not sorted alphabetically, so is it sorted by frequency? And also, is the sorting affected the calculation if I changed it to other sorting method (say, alphabetically)?

**Comment by jvking** [comment]
Yes it is sorted by frequency. Sorting does not affect the calculation.

**Comment by miqbal23** [comment]
Hello, I want to ask again

How do you interpret the result file, `result_Voc500.perf` and `result_Voc500.testscore`? I assume the `.testscore` is probability result of predicting the `test.feature` given `test.label` as label information

Also regarding information about the parameters, I think you should add information regarding which are mandatory (and which are optional), and also default value if the parameter is not supplied (table view should make it a good readability)

**Comment by jvking** [comment]
Yes that's the correct understanding.

**Comment by miqbal23** [comment]
Thank you very much for your help. I'm able to finish my assignment with this code 😄
